set_supervisior_pin:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    pin:
      required: true
      selector:
        text:
          multiline: false
set_authorised_user_pin:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: vogels_motion_mount_ble
    pin:
      required: true
      selector:
        text:
          multiline: false
